name: auto tag commit
on:
  push:
    branches:
      - master # Default release branch
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Get version
        id: getVersion
        uses: pchynoweth/action-get-npm-version@master

      - name: Determine if the tag exists
        uses: mukunku/tag-exists-action@v1.0.0
        id: checkTag
        with:
          tag: ${{ steps.getVersion.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add the tag and push
        if: ${{ steps.checkTag.outputs.exists == 'false' }}
        uses: mathieudutour/github-tag-action@v4.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.getVersion.outputs.version }}
          release_branches: deploy